### PR TITLE
Fix background select interpretation and 0:1 aspect ratio

### PR DESCRIPTION
**Pull request by j4james**
This PR fixes a bunch of issues in the way the background select is interpreted following our discussions in issue #5. It also includes a fix for the 0:1 aspect ratio which I had previously assumed to be an error (which would fallback to the macro parameter value), but is actually just rounded up to a minimum AR of 1:1.

### CODE REVIEW

**Review by hackerb9 — APPROVED** [review]
Ah! I had run into that problem with DECGNL not taking effect. So you're using `?` to draw an empty sixel ("graphics space"), which seems reasonable. This is reminiscent of how we had to have a character to get the proper region to clear instead of the whole screen. I had been appreciating `"` for fixing that problem because of the nice symmetry with DECGRA, but it doesn't help in this case, whereas `?` works for both. 

Is there any other character or sequence that might be more generally useful as the "solution" for getting fill to do the right thing? For example, adding graphics carriage return, `?$`, wouldn't ever be necessary, right?

**Comment by hackerb9** [comment]
Updated .png files are available with the results.

**Comment by j4james** [comment]
> Is there any other character or sequence that might be more generally useful as the "solution" for getting fill to do the right thing? For example, adding graphics carriage return, `?$`, wouldn't ever be necessary, right?

Oh you mean always putting that at the start of the image when you don't know what might follow? That's not a bad idea. Although if you're optimising images to the extent that you're getting a solitary `DECGNL` at the start of the image, you'd probably want to add a special case check for that and only output the `?` when absolutely necessary.

> Updated .png files are available with the results.

Thanks for that, but what happened to the `color_selection` output? The text background is black now, and it doesn't look like anything has changed in the test script. Could that be an issue with the screen capture script?

**Comment by hackerb9** [comment]
You're right. It should have been blue periods on white. I just ran the script again and it is white, not black, so I'm not sure what happened. 

I'll try running Media Copy again in 132- and 80-column mode and see if I can track it down. (As you may recall, background_select.sh in 80 column mode was the first screen image I found that consistently caused the VT340 to glitch when running Media Copy).

**Comment by j4james** [comment]
> You're right. It should have been blue periods on white. I just ran the script again and it is white, not black, so I'm not sure what happened.

OK cool. My one thought was the `DECGPBM` mode wasn't set (Graphics Print Background), but it looks like the mediacopy script already enables that automatically, so I don't know. Maybe it's just another glitch in the hardware.

**Pull request merged**
